services:
  postgres:
    image: postgres:15-alpine
    container_name: banco_de_dados
    environment:
      POSTGRES_DB: meu_projeto_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha_segura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=usuario
      - DB_PASSWORD=senha_segura
      - DB_NAME=meu_projeto_db
      - DB_PORT=5432
      - PORT=5000
    volumes:
      - ./backend:/src
      - /src/node_modules
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/src
      - /src/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge