# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      - DEBUG=True
      - DATABASE_PATH=/app/data/database.db
      - SECRET_KEY=your-secret-key-here
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

